version: "3.8"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000" # MinIO API
      - "9001:9001" # MinIO Console
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: svq
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
    command: >
      start-dev --hostname localhost
      --db=postgres
      --db-url=jdbc:postgresql://postgres:5432/svq
      --db-username=admin
      --db-password=password
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    entrypoint: ["/opt/keycloak/bin/kc.sh"]

volumes:
  minio_data:
  postgres_data:
